apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unit09-ingress
  namespace: unit09-backend
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: api.unit09.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: unit09-api
                port:
                  number: 80
    - host: dashboard.unit09.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: unit09-dashboard
                port:
                  number: 80
  tls:
    - hosts:
        - api.unit09.org
        - dashboard.unit09.org
      secretName: unit09-tls
