# Development environment configuration

app:
  env: development
  port: 3001
  logLevel: debug

solana:
  cluster: http://localhost:8899
  commitment: processed

security:
  allowedOrigins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
  enableRateLimit: false

database:
  host: localhost
  port: 5432
  user: dev_user
  password: dev_password
  name: unit09_dev
