apiVersion: v1
kind: Service
metadata:
  name: unit09-api
  namespace: unit09-backend
  labels:
    app: unit09-api
spec:
  type: ClusterIP
  selector:
    app: unit09-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: unit09-api-metrics
  namespace: unit09-backend
  labels:
    app: unit09-api
spec:
  type: ClusterIP
  selector:
    app: unit09-api
  ports:
    - name: metrics
      port: 9464
      targetPort: 9464
